#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}
config_dir="$config_home/tellico-qwen"
env_file="$config_dir/client.env"

usage() {
  cat <<'EOF'
usage: ./doctor.sh [--ssh-host HOST] [--remote-key-path PATH]

Checks everything the Tellico client needs, in dependency order, and prints
the single next step when something is missing. Safe to run before install.sh.
Values recorded by a previous install are used unless overridden here.
EOF
}

ssh_host=
remote_key_path=
while [ "$#" -gt 0 ]; do
  case $1 in
    --ssh-host)
      [ "$#" -ge 2 ] || { echo 'doctor: --ssh-host requires a value' >&2; exit 2; }
      ssh_host=$2
      shift 2
      ;;
    --remote-key-path)
      [ "$#" -ge 2 ] || { echo 'doctor: --remote-key-path requires a value' >&2; exit 2; }
      remote_key_path=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "doctor: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

# An existing install records the settings it was set up with. Command-line
# flags win over those, which win over the environment, as in the tunnel helper.
if [ -r "$env_file" ]; then
  # Generated by install.sh after validating each value.
  # shellcheck disable=SC1090
  . "$env_file"
fi
ssh_host=${ssh_host:-${TELLICO_SSH_HOST:-tellico}}
if [ -n "$remote_key_path" ]; then
  TELLICO_REMOTE_KEY_PATH=$remote_key_path
fi

. "$script_dir/lib/checks.sh"

echo "Tellico client doctor (ssh host: $ssh_host)"
echo

missing=
for command_name in ssh curl sed install opencode; do
  command -v "$command_name" >/dev/null 2>&1 || missing="$missing $command_name"
done
if [ -n "$missing" ]; then
  tellico_status_line tools FAIL "missing:$missing"
elif tellico_ssh_is_windows; then
  tellico_status_line tools WARN "ssh comes from Windows ($(command -v ssh))"
else
  tellico_status_line tools OK 'ssh, curl, sed, install, opencode'
fi

# Only meaningful once the commands exist.
path_warning=false
if [ -r "$config_dir/opencode.json" ]; then
  if tellico_bin_on_path; then
    tellico_status_line path OK "$HOME/.local/bin on PATH"
  else
    tellico_status_line path WARN "$HOME/.local/bin not on PATH"
    path_warning=true
  fi
fi

status=0
tellico_preflight || status=1

if [ "$status" -eq 0 ]; then
  tellico_check_allocation || status=1
fi

if [ -n "$missing" ]; then
  cat <<EOF

Next step: install the missing tools:$missing

  OpenCode comes from https://opencode.ai/docs/ and must be on PATH.
EOF
  status=1
elif tellico_ssh_is_windows; then
  cat <<EOF

Next step: this WSL session is using Windows' ssh.exe, which does not share
~/.ssh or the agent with the Linux side. Install the native client:

    sudo apt install openssh-client

EOF
  status=1
fi

if [ "$path_warning" = true ]; then
  profile=$(tellico_shell_profile)
  echo
  echo "Note: the client is installed, but $HOME/.local/bin is not on PATH,"
  echo 'so opencode-tellico will not be found.'
  echo
  if tellico_profile_sets_path "$profile"; then
    echo "  $profile already adds it; open a new terminal."
  else
    echo '  Add it with: ./install.sh --fix-path'
  fi
  echo
fi

if [ "$status" -eq 0 ]; then
  if [ "$path_warning" != true ]; then
    echo
  fi
  if [ ! -r "$config_dir/opencode.json" ]; then
    echo 'Everything checks out. Install the client: ./install.sh'
  elif [ "$path_warning" = true ]; then
    echo 'Everything else checks out.'
  else
    echo 'Everything checks out. Start a session: opencode-tellico 0'
  fi
fi

exit "$status"
