#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}
config_dir="$config_home/tellico-qwen"
env_file="$config_dir/client.env"

usage() {
  cat <<'EOF'
usage: ./doctor.sh [--gateway] [--gateway-url URL] [--ssh-host HOST]
                   [--remote-key-path PATH]

Checks everything the Tellico client needs, in dependency order, and prints
the single next step when something is missing. Safe to run before install.sh.
Values recorded by a previous install are used unless overridden here.

  --gateway          Check gateway mode against the built-in URL. Needed
                     only before the first install, which records the mode.
  --gateway-url URL  Check gateway mode against a different base URL.
EOF
}

ssh_host=
remote_key_path=
gateway_url=
while [ "$#" -gt 0 ]; do
  case $1 in
    --gateway)
      gateway_url=default
      shift
      ;;
    --gateway-url)
      [ "$#" -ge 2 ] || { echo 'doctor: --gateway-url requires a value' >&2; exit 2; }
      gateway_url=$2
      shift 2
      ;;
    --ssh-host)
      [ "$#" -ge 2 ] || { echo 'doctor: --ssh-host requires a value' >&2; exit 2; }
      ssh_host=$2
      shift 2
      ;;
    --remote-key-path)
      [ "$#" -ge 2 ] || { echo 'doctor: --remote-key-path requires a value' >&2; exit 2; }
      remote_key_path=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "doctor: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

# An existing install records the settings it was set up with. Command-line
# flags win over those, which win over the environment, as in the tunnel helper.
if [ -r "$env_file" ]; then
  # Generated by install.sh after validating each value.
  # shellcheck disable=SC1090
  . "$env_file"
fi
ssh_host=${ssh_host:-${TELLICO_SSH_HOST:-tellico}}
if [ -n "$remote_key_path" ]; then
  TELLICO_REMOTE_KEY_PATH=$remote_key_path
fi
# Before the first install there is no client.env to record the mode, so a
# gateway user has to say so. The URL itself comes from the checkout.
if [ "$gateway_url" = default ]; then
  gateway_url=${TELLICO_GATEWAY_URL:-}
  if [ -z "$gateway_url" ] && [ -r "$script_dir/config/gateway-url" ]; then
    gateway_url=$(sed -e 's/[[:space:]]*$//' -e '/^$/d' -e '1q' \
      "$script_dir/config/gateway-url")
  fi
  if [ -z "$gateway_url" ]; then
    echo 'doctor: no gateway URL is configured for this checkout.' >&2
    echo 'Pass one with --gateway-url https://HOST/v1' >&2
    exit 2
  fi
fi
if [ -n "$gateway_url" ]; then
  TELLICO_MODE=gateway
  TELLICO_GATEWAY_URL=${gateway_url%/}
fi

. "$script_dir/lib/checks.sh"

# Gateway mode has no SSH, no tunnel and no cluster account, so the whole
# middle of this script does not apply to it.
if tellico_is_gateway; then
  echo "Tellico client doctor (gateway mode: $(tellico_gateway_url))"
else
  echo "Tellico client doctor (ssh host: $ssh_host)"
fi
echo

missing=
if tellico_is_gateway; then
  doctor_commands='curl sed install opencode'
else
  doctor_commands='ssh curl sed install opencode'
fi
for command_name in $doctor_commands; do
  command -v "$command_name" >/dev/null 2>&1 || missing="$missing $command_name"
done
if [ -n "$missing" ]; then
  tellico_status_line tools FAIL "missing:$missing"
elif ! tellico_is_gateway && tellico_ssh_is_windows; then
  tellico_status_line tools WARN "ssh comes from Windows ($(command -v ssh))"
else
  tellico_status_line tools OK "$(echo "$doctor_commands" | tr ' ' ',' | sed 's/,/, /g')"
fi

# pi is the second harness and is optional: a device that only uses OpenCode is
# correctly installed without it, so its absence is reported rather than
# failed. install.sh writes the pi agent directory either way.
doctor_harnesses='opencode'
doctor_harnesses_missing=
for harness in pi crush; do
  if command -v "$harness" >/dev/null 2>&1; then
    doctor_harnesses="$doctor_harnesses, $harness"
  else
    doctor_harnesses_missing="$doctor_harnesses_missing $harness"
  fi
done
if [ -n "$doctor_harnesses_missing" ]; then
  tellico_status_line harnesses OK \
    "$doctor_harnesses; not installed:$doctor_harnesses_missing"
else
  tellico_status_line harnesses OK "$doctor_harnesses"
fi

# Crush is the only harness here that needs a line in a file outside this
# setup's own directory, so it is the only one that can be half-installed.
if [ -r "$config_dir/crush/tellico.crushrc" ]; then
  if grep -qF "$config_dir/crush/tellico.crushrc" \
    "$config_home/crush/crushrc" 2>/dev/null; then
    tellico_status_line crushrc OK 'sources the Tellico providers'
  else
    tellico_status_line crushrc WARN \
      "$config_home/crush/crushrc does not source tellico.crushrc"
  fi
fi

# Only meaningful once the commands exist.
path_warning=false
config_failed=false
drift_warning=false
if [ -r "$config_dir/opencode.json" ]; then
  if tellico_bin_on_path; then
    tellico_status_line path OK "$HOME/.local/bin on PATH"
  else
    tellico_status_line path WARN "$HOME/.local/bin not on PATH"
    path_warning=true
  fi

  if tellico_check_config "$config_dir/opencode.json" 2>/dev/null; then
    if [ -n "$(tellico_opencode_standalone_flag)" ]; then
      tellico_status_line config OK 'both providers present, --standalone'
    else
      tellico_status_line config OK 'both providers present, shared service'
    fi
  else
    tellico_status_line config FAIL 'providers missing from opencode.json'
    config_failed=true
  fi

  # OpenCode reads the installed copies, not this checkout, so an edit here
  # that was never installed looks exactly like a change that did not work.
  if tellico_check_drift "$script_dir" "$config_dir" "$HOME/.local/bin"; then
    tellico_status_line installed OK 'copies match this checkout'
  else
    drift_detail=
    if [ -n "$tellico_drifted" ]; then
      drift_detail="stale:$tellico_drifted"
    fi
    if [ -n "$tellico_drift_absent" ]; then
      drift_detail="${drift_detail:+$drift_detail, }absent:$tellico_drift_absent"
    fi
    tellico_status_line installed WARN "$drift_detail"
    drift_warning=true
  fi
fi

status=0
if tellico_is_gateway; then
  tellico_check_gateway "$config_dir/api-key" || status=1
else
  tellico_preflight || status=1

  if [ "$status" -eq 0 ]; then
    tellico_check_allocation || status=1
  fi
fi

if [ "$config_failed" = true ]; then
  cat <<EOF

Next step: $config_dir/opencode.json does not declare both node providers.
Reinstall it from a clean checkout:

    ./install.sh

EOF
  status=1
fi

if [ -n "$missing" ]; then
  cat <<EOF

Next step: install the missing tools:$missing

  OpenCode comes from https://opencode.ai/docs/ and must be on PATH.
EOF
  status=1
elif ! tellico_is_gateway && tellico_ssh_is_windows; then
  cat <<EOF

Next step: this WSL session is using Windows' ssh.exe, which does not share
~/.ssh or the agent with the Linux side. Install the native client:

    sudo apt install openssh-client

EOF
  status=1
fi

if [ "$drift_warning" = true ]; then
  echo
  echo 'Note: the installed copies differ from this checkout, so a session is'
  echo 'running the older files. Install them and restart OpenCode:'
  echo
  echo '  ./install.sh --no-start   # safe while a session is live'
  echo
fi

if [ "$path_warning" = true ]; then
  profile=$(tellico_shell_profile)
  echo
  echo "Note: the client is installed, but $HOME/.local/bin is not on PATH,"
  echo 'so opencode-tellico will not be found.'
  echo
  if tellico_profile_sets_path "$profile"; then
    echo "  $profile already adds it; open a new terminal."
  else
    echo '  Add it with: ./install.sh --fix-path'
  fi
  echo
fi

if [ "$status" -eq 0 ]; then
  if [ "$path_warning" != true ]; then
    echo
  fi
  if [ ! -r "$config_dir/opencode.json" ]; then
    if tellico_is_gateway; then
      echo 'Everything checks out. Install the client:'
      echo "  ./install.sh --gateway-url $(tellico_gateway_url)"
    else
      echo 'Everything checks out. Install the client: ./install.sh'
    fi
  elif [ "$path_warning" = true ] || [ "$drift_warning" = true ]; then
    echo 'Everything else checks out.'
  else
    echo 'Everything checks out. Start a session: opencode-tellico 0'
  fi
fi

exit "$status"
