#!/bin/sh
# Install the Tellico Qwen API gateway on this host.
#
# The gateway is the optional second way in: users get a URL and their own API
# key instead of an SSH tunnel. It sits on top of the client install, reusing
# tellico-qwen-tunnel's forwards and cluster key, and it never restarts that
# tunnel -- a live opencode session is safe while this runs.
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}
client_dir="$config_home/tellico-qwen"
config_dir="$config_home/tellico-gateway"
env_file="$config_dir/gateway.env"
lib_dir="$HOME/.local/lib/tellico-gateway"
bin_dir="$HOME/.local/bin"
unit_dir="$config_home/systemd/user"
unit_name=tellico-gateway.service

start=1
want_bind=''
want_port=''
want_inflight=''

usage() {
  cat >&2 <<'USAGE'
usage: gateway/install-gateway.sh [options]

  --bind ADDR        address the gateway listens on (default: 127.0.0.1)
  --port PORT        port the gateway listens on (default: 4000)
  --max-inflight N   cluster slots the gateway may hold at once (default: 4)
  --no-start         install files only; do not start the service
USAGE
  exit 2
}

while [ $# -gt 0 ]; do
  case $1 in
    --bind) want_bind=${2:?--bind needs a value}; shift 2 ;;
    --port) want_port=${2:?--port needs a value}; shift 2 ;;
    --max-inflight) want_inflight=${2:?--max-inflight needs a value}; shift 2 ;;
    --no-start) start=0; shift ;;
    -h|--help) usage ;;
    *) echo "install-gateway.sh: unknown option $1" >&2; usage ;;
  esac
done

fail() {
  echo "install-gateway.sh: $1" >&2
  shift
  for line in "$@"; do
    echo "  $line" >&2
  done
  exit 1
}

# --- prerequisites -----------------------------------------------------------

for tool in python3 curl awk; do
  command -v "$tool" >/dev/null 2>&1 ||
    fail "$tool is required but not on PATH."
done

[ -s "$client_dir/api-key" ] ||
  fail 'the client side is not installed yet.' \
    'The gateway reuses its cluster key and port forwards. From the repo root:' \
    '  ./install.sh' \
    'Then rerun this script.'

command -v "$bin_dir/tellico-qwen-tunnel" >/dev/null 2>&1 ||
  [ -x "$bin_dir/tellico-qwen-tunnel" ] ||
  fail 'tellico-qwen-tunnel is not installed.' \
    'Run ./install.sh from the repository root first.'

# --- existing settings become the defaults, so reruns are safe ---------------

if [ -r "$env_file" ]; then
  # shellcheck disable=SC1090
  . "$env_file"
fi

# The tunnel's local ports are whatever install.sh was told to use.
port0=18080
port1=18081
if [ -r "$client_dir/client.env" ]; then
  # shellcheck disable=SC1090
  . "$client_dir/client.env"
  port0=${TELLICO_QWEN_PORT0:-$port0}
  port1=${TELLICO_QWEN_PORT1:-$port1}
fi

# Keep the advertised context equal to the per-slot figure in opencode.json,
# which is the number the cluster actually serves. See AGENTS.md.
context=$(python3 -c '
import json, sys
config = json.load(open(sys.argv[1]))
limits = {
    model["limit"]["context"]
    for provider in config["provider"].values()
    for model in provider["models"].values()
}
print(limits.pop() if len(limits) == 1 else 131072)
' "$repo_dir/config/opencode.json" 2>/dev/null) || context=131072

bind=${want_bind:-${TELLICO_GATEWAY_BIND:-127.0.0.1}}
port=${want_port:-${TELLICO_GATEWAY_PORT:-4000}}
inflight=${want_inflight:-${TELLICO_GATEWAY_MAX_INFLIGHT:-4}}
model=${TELLICO_GATEWAY_MODEL:-qwen3.6-35b-a3b}
model_aliases=${TELLICO_GATEWAY_MODEL_ALIASES-qwen3.8-27b}

case $port in ''|*[!0-9]*) fail "--port must be a number, got '$port'" ;; esac
case $inflight in ''|*[!0-9]*) fail "--max-inflight must be a number" ;; esac
[ "$inflight" -ge 1 ] || fail '--max-inflight must be at least 1'
[ "$inflight" -le 6 ] || echo 'install-gateway.sh: warning: Tellico has 6 slots cluster-wide; a higher --max-inflight will just queue.' >&2

# --- install files -----------------------------------------------------------

umask 022
mkdir -p "$lib_dir" "$bin_dir"
install -m 0644 "$repo_dir/gateway/tellico_gateway.py" "$lib_dir/tellico_gateway.py"
install -m 0644 "$repo_dir/gateway/tellico_monitor.py" "$lib_dir/tellico_monitor.py"
install -m 0755 "$repo_dir/gateway/bin/tellico-gateway" "$bin_dir/tellico-gateway"

mkdir -p "$config_dir"
chmod 700 "$config_dir"

# gateway.env holds no secrets: the cluster key stays in its own 0600 file and
# user keys are stored only as hashes.
umask 077
cat >"$env_file" <<EOF
# Generated by gateway/install-gateway.sh. Edit, then: tellico-gateway restart
TELLICO_GATEWAY_BIND="$bind"
TELLICO_GATEWAY_PORT="$port"
TELLICO_GATEWAY_KEYS="$config_dir/keys"
TELLICO_GATEWAY_UPSTREAM_KEY="$client_dir/api-key"
TELLICO_GATEWAY_NODES="node0=127.0.0.1:$port0 node1=127.0.0.1:$port1"
TELLICO_GATEWAY_SCRIPT="$lib_dir/tellico_gateway.py"

# How many of the cluster's 6 slots the gateway may hold. The default leaves
# two free for a direct opencode-tellico session.
TELLICO_GATEWAY_MAX_INFLIGHT="$inflight"
TELLICO_GATEWAY_DEFAULT_MAX_PARALLEL="${TELLICO_GATEWAY_DEFAULT_MAX_PARALLEL:-1}"
TELLICO_GATEWAY_QUEUE_TIMEOUT="${TELLICO_GATEWAY_QUEUE_TIMEOUT:-120}"
TELLICO_GATEWAY_REQUEST_TIMEOUT="${TELLICO_GATEWAY_REQUEST_TIMEOUT:-3600}"

TELLICO_GATEWAY_MODEL="$model"
# Old model ids that still route to the current one, so clients configured
# before a model swap keep working.
TELLICO_GATEWAY_MODEL_ALIASES="$model_aliases"
TELLICO_GATEWAY_CONTEXT="$context"
EOF
chmod 600 "$env_file"
echo "Installed $lib_dir/tellico_gateway.py"
echo "Installed $lib_dir/tellico_monitor.py"
echo "Installed $bin_dir/tellico-gateway"
echo "Wrote     $env_file"

# --- service -----------------------------------------------------------------

have_systemd_user() {
  command -v systemctl >/dev/null 2>&1 &&
    systemctl --user is-system-running >/dev/null 2>&1
}

if have_systemd_user; then
  umask 022
  mkdir -p "$unit_dir"
  sed \
    -e "s|__TELLICO_GATEWAY_ENV__|$env_file|g" \
    -e "s|__TELLICO_GATEWAY_PYTHON__|$(command -v python3)|g" \
    -e "s|__TELLICO_GATEWAY_SCRIPT__|$lib_dir/tellico_gateway.py|g" \
    "$repo_dir/systemd/$unit_name.in" >"$unit_dir/$unit_name"
  chmod 644 "$unit_dir/$unit_name"
  systemctl --user daemon-reload
  systemctl --user enable "$unit_name" >/dev/null
  echo "Enabled   $unit_dir/$unit_name"
else
  echo 'No systemd user manager here, so the gateway has no service unit.'
  echo 'Run it in the foreground (or under your own supervisor) with:'
  echo '  tellico-gateway run'
  start=0
fi

if [ "$start" -eq 1 ]; then
  echo
  # restart waits for /health, so a slow first poll is not reported as failure.
  if ! "$bin_dir/tellico-gateway" restart; then
    echo >&2
    echo 'The gateway did not come up. Look at:' >&2
    echo '  tellico-gateway doctor' >&2
    echo '  journalctl --user -u tellico-gateway -n 50' >&2
    exit 1
  fi
  "$bin_dir/tellico-gateway" status
fi

echo
echo 'Next:'
echo "  tellico-gateway add-user alice      # mint a key, printed once"
echo "  tellico-gateway expose              # publish it over Tailscale Funnel"
echo "  tellico-gateway doctor              # check the whole path"
echo "  tellico-gateway monitor             # watch users and load"
